version: '3'
services:
  ghost-blog:
    image: ghost:1-alpine
    networks:
      - my-network
    ports:
      - 2368:2368
    depends_on:
      - db
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ${MYSQL_ROOT_PASSWORD}
      database__connection__database: ghost

  db:
    image: mysql:5.7
    networks:
      - my-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${PWD}/database:/var/lib/mysql

networks:
  my-network:
      driver: bridge

volumes:
  mysql_data:
      driver: local